Fix build

diff --git a/dev/build-site b/dev/build-site
--- a/dev/build-site
+++ b/dev/build-site
@@ -1,13 +1,12 @@
-#!/bin/bash
+#!/bin/sh
 
 cd "$( dirname "${BASH_SOURCE[0]}" )"
+cd ..
 
 function build_site {
 	if [[ $1 == "v1."* ]]; then
-
-		return "
-
-		"
+		mkdir -p dist
+		touch dist/index.html
 	else
 		NODE_VERSION="18.16.0"
 
@@ -39,7 +38,34 @@ function install_nvm {
 	bash "$HOME/.nvm/nvm.sh"
 }
 
-BUILD_DIR="../docker-build"
+CURRENT_BRANCH=$(git branch --show-current)
+CURRENT_DETHEAD_VALUE=$(git config advice.detachedHead)
+git config advice.detachedHead false
+
+function clean_up {
+	git checkout $CURRENT_BRANCH
+	git config advice.detachedHead "$CURRENT_DETHEAD_VALUE"
+}
+
+function on_exit() {
+	echo "Program is exiting, cleaning up"
+	clean_up
+	exit 0
+}
+
+function on_error() {
+	echo "Program has errored, cleaning up"
+	clean_up
+	rm -rf $BUILD_DIR
+	rm -rf dist
+	exit 1
+}
+
+trap on_error ERR
+trap on_exit SIGINT
+
+BUILD_DIR="docker-build"
+rm -rf $BUILD_DIR
 mkdir -p $BUILD_DIR
 
 echo "Fetching site versions"
@@ -55,13 +81,15 @@ do
 	echo "Building site version $version"
 	build_site $version
 
-	$version_dir_name=(echo $version | sed 's/\./_/g')
-	$version_dir="$BUILD_DIR/$version_dir_name"
+	version_dir_name=${version//./_}
+	version_dir="$BUILD_DIR/$version_dir_name"
 	mkdir -p $version_dir
-	echo "Copying build to $BUILD_DIR/$version"
+	echo "Copying build to $version_dir"
 	cp -r dist/* $version_dir
 
 	rm -rf dist
 
 	echo "Finished building version $version"
 done
+
+clean_up
